mode:
 - DocuMind
docuMind-model: "gemini/gemini-1.5-pro-latest"
docuMind-db: ".SourceSageAssets\\DOCUMIND\\Repository_summary.md"
docuMind-release-report: ".SourceSageAssets\\RELEASE_REPORT\\Report_v5.1.1.md"
docuMind-changelog: ".SourceSageAssets\\Changelog\\CHANGELOG_release_5.1.1.md"
docuMind-output: ".SourceSageAssets/DOCUMIND/RELEASE_NOTES_v5.1.1.md"
docuMind-prompt-output: ".SourceSageAssets/DOCUMIND/_PROMPT_v5.1.1.md"
repo-name: "SourceSage"
repo-version: "v5.1.1"