ss-mode:
 - DocuMind
docuMind-model: "gemini/gemini-1.5-pro-latest"
docuMind-db: ".SourceSageAssets/Repository_summary.md"
docuMind-release-report: ".SourceSageAssets/RELEASE_REPORT/Report_v5.6.0.md"
docuMind-changelog: ".SourceSageAssets/Changelog/CHANGELOG_main.md"
docuMind-output: ".SourceSageAssets/RELEASE_NOTES_v5.6.0.md"
docuMind-prompt-output: ".SourceSageAssets/_PROMPT_v5.6.0.md"
repo-name: "SourceSage"
repo-version: "v5.6.0"

# sourcesage --ss-mode=DocuMind --yaml-file=docs\.sourcesage_releasenotes.yml
